### ISSUE TITLE
how to get file with selected segmentations in struct file

### ISSUE THREAD

**Issue by nataschadam** [brianmanderson/Dicom_RT_and_Images_to_Mask#1]
hello, tahnk you for your script. I have a question, I need to create a single segmentation file containing single segmentations of the struct file. 
For example my struct file has the following segmentations: 
Body
CTV
Heart
PTV
lungdx
lungsx
Trachea
lung-PTV
GTV N
GTV T

Now I need to create three files .nrrd, one containing the segmentation GTV N and GTV T, one containing CTV and one PTV.

How can I do it? Thanks!!!

**Comment by brianmanderson** [comment]
If you want a single segmentation file, run the .get_mask() multiple times for each contour name and save your output
I'm sorry, I'm not familiar with .nrrd files, but I'm sure there is some Numpy -> .nrred converter or SimpleITK
