### ISSUE TITLE
Skimage.draw.polygon yields incorrect polygons

### ISSUE THREAD

**Issue by evan-porter** [brianmanderson/Dicom_RT_and_Images_to_Mask#11]
The use of skimage.draw.polygon() in RTstruct reconstruction is not recommended because it is inconsistent in inclusion of surface coordinates (see plot below where blue is the RTStruct coordinates and yellow is the filled polygon coordinates). The function cv2.fillpoly() resolves this issue as well as running faster. I can submit the modification in a pull request if desired.

![image](https://user-images.githubusercontent.com/7144894/108871806-6c54d880-75f1-11eb-942f-e6009fd361dd.png)

**Comment by brianmanderson** [comment]
Hi @evan-porter if you have a modification in mind that will correct the issue, please make the pull, I'll validate and merge

Thank you for finding this!

**Comment by brianmanderson** [comment]
Thank you very much! I have merged the branch and am closing the ticket ^^
