### ISSUE TITLE
Problem with nifti2RTStructure conversion

### ISSUE THREAD

**Issue by ptahery** [brianmanderson/Dicom_RT_and_Images_to_Mask#14]
Hi Brian,

Thank you so much for sharing Dicom-RT-tool
I want to convert my model's prediction mask to RTStructure.
I follow the example you wrote. But my prediction's shape is like the image's shape (e.g. (236, 512, 512)).

So I've got this error:

AssertionError: Your last dimension of prediction array should be equal  to the number or ROI_names minus 1, channel 0 is background

What should I do?

I thank you for your consideration.
Best,
Parisa

**Comment by brianmanderson** [comment]
Hi Parisa,

I'm glad you enjoy the tool, and I'm sorry for the trouble you've been having! If your output prediction is one class, then your prediction shape should be (236, 512, 512, 2), where your binary image should be the last channel. The idea is that a neural network should have a 'background' class, and then your prediction class.

You can get around this by saying:

prediction = np.concatenate([prediction[..., None], prediction[..., None]], axis=-1)

The prediction[..., None] expands the last dimension, so you now have (236, 512, 512, 1), and the concatenate just stacks this ontop of itself

Please reach out if this does not solve your problem, or you need further guidance

Best,
Brian

**Comment by brianmanderson** [comment]
Also, @ptahery if you could please write a copy of the code that you're using to write the prediction that would be very helpful

Thank you,
Brian

**Comment by brianmanderson** [comment]
@ptahery I haven't heard anything about this in the last 10 days, closing for now. Please reach out if the presented solution does not work

Thank you!
Brian

**Comment by ptahery** [comment]
Hi Brian,

I'm sorry for the delay.
Thanks. My problem is solved.

Just another question. Is it possible to convert a CNN prediction (with nifti format) to RT-Structure directly?

I mean, as far as I understand for conversion to RT, an index is needed and for indexing of CT images, an RT-Structure is needed.
I was able to do this procedure for a nifti mask while an RT-Structure was also existed for indexing (according to ROIs).
So, how we can index the CT images while we don't have RT-Structure files, and we only have the CT image and nifti mask prediction from CNN (as we don't have RTStructure most of the time and this is the reason of using CNN).

Many thanks and best,
Parisa

**Comment by brianmanderson** [comment]
Hi Parisa,

You will need a set of CT images to create an RT-Structure.

I'm sorry but I don't entirely know what you mean by 'for indexing of CT images, an RT-Structure is needed'. You can create an RT-Structure without one being present. The 'template-RT' structure file present within this folder is just a template, you can create one from scratch if you wish.

For a details on how to turn a prediction into an RT-Structure, please refer to the 'Examples' folder. The bottom section titled 'Predictions to RT-Structure Example'.

You will want to use the DicomReader to read the CT images (RT-Structures are not required), then use the .prediction_array_to_RT(prediction_array=array, output_dir=path, ROI_Names=['list_of_predictions'])

Please tell me if this helps,
Brian

**Comment by ptahery** [comment]
Hi Brian
I thank you so much for your reply. Yes, it works now!

Loading images for None at 
 /Users/paris/Desktop/test/Image_Data\CT-image\lung_112\09-20-2006-1-96508\4.000000-24533

Running off a template
Writing data for test
Writing out data.../Users/paris/Desktop/test/RT_Structures
Finished!

Many thanks and best regards,
Parisa
