### ISSUE TITLE
Normalization of Pixel Spacing

### ISSUE THREAD

**Issue by JKDomoguen** [brianmanderson/Dicom_RT_and_Images_to_Mask#20]
Hi your library is super helpful, thank you for your wonderful work.
I hope to rather ask some details on the conversion from dicom files to a single array/tensor object.
Specifically, are the pixel spacing in the DCM file normalized or as is?
I have CT scan with thickness of 3mm but pixel spacing for both row and colum are [0.75mm,0.75mm], I hope to normalize each voxels to 1x1x3 mm.

Thank you.

**Comment by brianmanderson** [comment]
Hi Jansen,

The pixel spacing is 'as is'. We do not normalize the slice spacing in any way from the native values. If you created the nifti files, they will have spacing (0.75mm, 0.75mm, 3mm)

If you want to resample them to be (1x1x3mm) you should use our Resample class https://github.com/brianmanderson/Resample_Class

You can install it with 

`pip install NiftiResampler`

Then

```
from NiftiResampler.ResampleTools import ImageResampler, sitk
Resampler = ImageResampler()
base_image = sitk.ReadImage(image_path)  # Your saved nifti file
desired_dimensions = (1.0, 1.0, 3.0)  # Your 1x1x3 specification

resampled = Resampler.resample_image(input_image_handle=base_image, ref_resampling_handle=None, output_spacing=desired_dimensions, interpolator='Linear')
```

Hope this helps
Brian

**Comment by JKDomoguen** [comment]
I see got it. 
Thanks Brian for your time and your absolutely great work!

**Comment by JKDomoguen** [comment]
Hello Brian, 
But I am having some problems. 
So I am using a deep learning model to output a segmentation mask from a pre-processed dicom series.
Pre-processed means it has been resampled to the desired dimension (1.0 x 1.0 x 3.0 ) then normalized then fed to the deep learning model to get the output segmentation mask.

So after getting the segmentation mask which is an array, I convert it back to  an RT-struct file format for radiologist to use in their 3rd part software such as **3D Slicer**. 

My problem is, when I resample the output segmentation mask to its original pixel spacing as well as using the original dicom_handle as reference SITK Image, it returns all zero values without the mask.
I suspect the main culprit is the origin of the original dicom series. 

I hope to ask if you know a better method of making an inverse transform on the segmentation mask output to arrive in the original segmentation mask. 
Or better yet, a resampling tool that will preserve the information of the source image.

Thank you for your time.
