### ISSUE TITLE
Write output for multiple RS associated with single CT

### ISSUE THREAD

**Issue by RafeMcBeth** [brianmanderson/Dicom_RT_and_Images_to_Mask#23]
Hi Brian! Thank you for sharing this fantastic tool. 

When using the write_parallel function, Is it possible to write out multiple RS masks to .nii.gz files and corresponding excel file? My data folders contain the CT scan and 2 RS files (clinical_1, clinical_2) in the same folder as the CT scan.  

Dicom_reader has no problem identifying and adding the different RS files to the dictionaries, but when writing out using the write_parallel function, it seems only to write out the masks for a single RS file. I tried to quickly implement a write_parallel_mult calling the get_images_and_mask_mult function, but I think I'm missing something. 

Any help would be greatly appreciated. 

Best Regards, 
Rafe

**Comment by brianmanderson** [comment]
Hi Rafe,

No problem! I'm glad it's been somewhat helpful for you. Sorry for the delay in response, does this mean that you were able to solve your issue?

Best,
Brian
