### ISSUE TITLE
Numpy deprecation causing issue

### ISSUE THREAD

**Issue by ddicostanzo** [brianmanderson/Dicom_RT_and_Images_to_Mask#25]
Hi Brian, I've run into an issue with your library. It was working fine for awhile, but numpy has recently updated and deprecated the `np.bool` type in favor of `np.bool_`. In the poly2mask method, it currently is using the `np.bool` which throws a combination of Attribute and Key errors at the return statement. I downloaded the source and made the modification locally. That seemed to do the trick and the masks are now available without errors.

If it helps, I'm using numpy 1.24.1. The requirements for this library don't specify a version number. 

[Reference to numpy docs](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated)

**Comment by brianmanderson** [comment]
Hi Dominic,

Thanks so much for finding this and providing a solution! Do you want/know how to make a pull request? I can make the fix myself if you like, but this way you will be added as one of the contributors to the project! It's always nice to see someone find bugs and improve the repo

I can hop on a zoom call with you if you'd like to go through the process

Best,
Brian

**Comment by ddicostanzo** [comment]
Thanks Brian. I've created a pull request (or at least I think I did). This was my first time doing it, so let me know if I need to make any modifications.

**Comment by brianmanderson** [comment]
Looked great! Nicely done! Thank you for contributing to the project =)
