### ISSUE TITLE
DICOM loading fails if file extensions are '.DCM' in upper-caps

### ISSUE THREAD

**Issue by juandoso** [brianmanderson/Dicom_RT_and_Images_to_Mask#28]
DICOM file sets with names in all-caps (including having extension .DCM) are not common but exist, and **walk_through_folders** and **add_dicom_to_dictionary_from_path** fail with them. Adding support for both '.dcm' and '.DCM' extensions require only minor modifications

https://github.com/brianmanderson/Dicom_RT_and_Images_to_Mask/blob/e732eeeabe70a73ee963f5c09d8f063300e9f71a/src/DicomRTTool/ReaderWriter.py#L858

**Comment by brianmanderson** [comment]
Hi Juan,

Thanks for the improvement! This has been addressed now in commit ce3d03d61580f89d3205f66f6cf52853b123a440

Cheers,
Brian
