### ISSUE TITLE
np.unique(mask)

### ISSUE THREAD

**Issue by shawoo030** [brianmanderson/Dicom_RT_and_Images_to_Mask#32]
I followed the example of Tutorial you shared.
In Part 1, after following code,

pt_indx = indexes[0] 
dcm_reader.set_index(pt_indx) # This index has all the structures, corresponds to pre-RT T1-w image for patient 011
dcm_reader.get_images_and_mask() # Load up the images and mask for the␣ requested index

image = dcm_reader.ArrayDicom # image array
mask = dcm_reader.mask # mask array

I got [0,1,2] for np.unique(mask)

This makes problem when I calculate DSC score...
How can I get just 0 and 1 values for mask??

**Comment by brianmanderson** [comment]
Hi Shawoo,

You can set the attribute to be arg_max=False in the dcm_reader build statement. This will transform your mask from [Number of slices, 512, 512] to be [Number of slices, 512, 512, Number of classes + 1], with the first channel being background

Brian
