### ISSUE TITLE
dose handle issue from version 0.4.2 to version 1.0.0

### ISSUE THREAD

**Issue by karim1871** [brianmanderson/Dicom_RT_and_Images_to_Mask#33]
Hi, thank you for your great work. 

I have an issue with the dose data starting version 1.0.0.

code:  
            Dicom_reader = DicomReaderWriter(description='', arg_max=True, get_dose_output=True)
            Dicom_reader.set_contour_names_and_associations(Contour_Names=Contour_Names, associations=associations)
            Dicom_reader.walk_through_folders(patient_folder) # need to define in order to use all_roi method
            
            all_rois = Dicom_reader.return_rois(print_rois=False)  # Return a list of all rois p#esent, and print them
            series = Dicom_reader.series_instances_dictionary  
            indexes = Dicom_reader.which_indexes_have_all_rois() 

            Dicom_reader.set_index(x)  
            Dicom_reader.get_images_and_mask() 
            Dicom_reader.get_dose()  
            
            
            image_handle = Dicom_reader.dicom_handle 
            mask_handle = Dicom_reader.annotation_handle 
            dose_handle = Dicom_reader.dose_handle

I can get the dose data and handle with the version 0.4.2 but not with the versions starting at 1.0.0 (RDs list in the dictionnary is empty )

**Comment by brianmanderson** [comment]
Hi Karim,

I'll look into this, thank you!

Brian

**Comment by brianmanderson** [comment]
I found an issue that was not properly catching the plan which dropped the dose. The change for dose files was focused on bd1eaca1ff3238dedf781a3be91389856347075b where Halcyon plans don't always have a referenced structure set. When you are running this, do you also have the plan, along with the structure set and images? Or just the images, structure set, and dose files?

**Comment by karim1871** [comment]
Hi, i get the warning message "Had an error loading " while reading the RTplan dicoms. I have the same error in 0.4.2 and 1.0.0. Looks like 0.4.2 is more permissive and doesnt need the RTplan infos.

**Comment by brianmanderson** [comment]
I pushed an update 2.0.10, please try that one out. Sorry, trying to add more functionality sometimes breaks things =(

**Comment by karim1871** [comment]
same issue

![Screenshot 2023-09-14 161135](https://github.com/brianmanderson/Dicom_RT_and_Images_to_Mask/assets/101674722/ebebfbe9-4a80-4732-bebd-cf7b30107066)

**Comment by brianmanderson** [comment]
Any chance you could anonymize the data and put it on a google drive for me to look at?

**Comment by karim1871** [comment]
Hi Brian, i will get back to you tomorrow.

**Comment by brianmanderson** [comment]
I'm free to hop on a zoom call within the next few hours if that would work better

**Comment by karim1871** [comment]
Sorry, i thought i could get you an anonymized patient today but it will have to wait next week. I will get back to you as soon as i get a patient that i can send you.

**Comment by brianmanderson** [comment]
The reason that the old one works, but not the new one, is that the old version would only check based on the StudyInstanceUID. The newer version directly checks against the ReferencedStructureSetSequence SOPIntanceUID. The more updated version is definitely more stable when multiple dose files are being analyzed. What machine is the dose file coming from? C-arm, truebeam, infinity, halcyon?

**Comment by karim1871** [comment]
patients came from eclipse. It was a direct database query, not a manual export from the tps.

**Comment by brianmanderson** [comment]
Is it possible for you to pull the plans along with the dose?

**Comment by karim1871** [comment]
Hi Brian, could you send me your email address?

**Comment by brianmanderson** [comment]
markba122@gmail.com

I just added a new function called group_dose_by_frame_of_reference, it defaults to 'True'. The goal is that if dose files remain after compiling, they are associated with images with the same study instance UID and frame of reference UID.

Please try it out and tell me if it fixes your issue

**Comment by karim1871** [comment]
files sent.

**Comment by karim1871** [comment]
Hi Brian, 
i tested the new version.  No more issue with the dose handle.
Worked with the patients from database and exported directly from tps. 

Great work. Thank you

**Comment by brianmanderson** [comment]
Great, closing issue
