### ISSUE TITLE
How is maks.nii converted to DicomRT?

### ISSUE THREAD

**Issue by SuperLuckyKris** [brianmanderson/Dicom_RT_and_Images_to_Mask#38]
How to produce a dicomRT with a mask.nii and a dicom original image

**Comment by brianmanderson** [comment]
Hi, I'm sorry that I don't fully understand the question. A series of steps for converting a dicomRT structure and the associated image file are presented in the 'Examples' folder: https://github.com/brianmanderson/Dicom_RT_and_Images_to_Mask/tree/main/Examples

Please tell me if this helps
