### ISSUE TITLE
AttributeError: 'DicomReaderWriter' object has no attribute 'dicom_names

### ISSUE THREAD

**Issue by Abderaoufbhc** [brianmanderson/Dicom_RT_and_Images_to_Mask#5]
Dicom slices and The RTStruct.dcm are in the Same folder, I get this error : 

/usr/local/lib/python3.6/dist-packages/DicomRTTool.py in Contours_to_mask(self, index)
    397 
    398     def Contours_to_mask(self, index):
--> 399         mask = np.zeros([len(self.dicom_names), self.image_size_rows, self.image_size_cols], dtype='int8')
    400         Contour_data = self.RS_struct.ROIContourSequence[index].ContourSequence
    401         for i in range(len(Contour_data)):

AttributeError: 'DicomReaderWriter' object has no attribute 'dicom_names

**Comment by brianmanderson** [comment]
Hello,

Could you please provide the input parameters that you are using when you get the error?

For example:

`from DicomRTTool import DicomReaderWriter`

`path = 'xxx'`

`dicomreader = DicomReaderWriter()`
`dicomreader(path)`

**Comment by brianmanderson** [comment]
@Abderaoufbhc Hello, just checking to see if there's been an update on this

Best,
Brian

**Comment by brianmanderson** [comment]
@Abderaoufbhc I'll be closing this as I haven't heard anything, please feel free to reopen if you need
