### ISSUE TITLE
the output

### ISSUE THREAD

**Issue by GuobinZhangTJU** [brianmanderson/Dicom_RT_and_Images_to_Mask#6]
Hi, the ouput of "Dicom_reader.with_annotations(pred,output_path,ROI_Names=['test'])" is not nii???
there are two "path " in your offered samples....

**Comment by GuobinZhangTJU** [comment]
the code you provided in "http://aapmchallenges.cloudapp.net/forums/3/2/" can not generate "mask".nii,
how to generate the organs' mask you answered in  "http://aapmchallenges.cloudapp.net/forums/3/2/"

**Comment by brianmanderson** [comment]
Hi @GuobinZhangTJU , I apologize for the delay
No, the output from with_annotation is a .dcm RT structure file, with_annotations is assuming that you have predicted on some form of model and are now creating the RT structure

If you want the dicom image/mask as a .nii file, please do the following
```
from DicomRTTool import DicomReaderWriter, sitk, os
Contour_Names = ['Liver']
associations = {'Liver_BMA_Program4':'Liver','Liver':'Liver'}
path = 'C:\users\brianmanderson\Patients\Patient_1\CT_1\'
Dicom_reader = DicomReaderWriter(get_images_mask=True, Contour_Names=Contour_Names, associations=associations)

Dicom_reader.Make_Contour_From_directory(path)
image_nifti_handle = Dicom_reader.dicom_handle
mask_nifti_handle = Dicom_reader.annotation_handle
```
If you then want to _save_ this handle as a .nii file, you can do this with SimpleITK
`sitk.WriteImage(mask_nifti_handle, os.path.join('.', 'mask.nii')`
`sitk.WriteImage(image_nifti_handle, os.path.join('.', 'image.nii')`

**Comment by brianmanderson** [comment]
@GuobinZhangTJU I have not heard anything new update in 30 days, so closing the ticket. Please feel free to reopen it if the trouble continues
